# Generated by Django 2.2.19 on 2021-04-10 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BestOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('motor_driver_type', models.BooleanField()),
                ('cover', models.BooleanField()),
                ('filament_chamber', models.BooleanField()),
                ('ups_module', models.BooleanField()),
                ('abl', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('price', models.IntegerField()),
                ('outgoing', models.FloatField()),
                ('belonging_order_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('dhaka', 'Dhaka'), ('rajshahi', 'Rajshahi'), ('rangpur', 'Rangpur'), ('sylhet', 'Sylhet'), ('khulna', 'Khulna'), ('chittagong', 'Chittagong'), ('barishal', 'Barishal')], max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('profile_status', models.CharField(choices=[('not_verified', 'not_verified'), ('verified', 'verified'), ('pending', 'pending'), ('new', 'new')], default='new', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
