# Generated by Django 2.2.19 on 2021-04-16 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_bestoffers_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestoffers',
            name='bed_size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bestoffers',
            name='height',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='orders_without_trxID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('bed_size', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('motor_driver_type', models.BooleanField()),
                ('cover', models.BooleanField()),
                ('filament_chamber', models.BooleanField()),
                ('ups_module', models.BooleanField()),
                ('abl', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
