# Generated by Django 2.2.19 on 2021-04-16 09:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20210416_0929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders_without_trxID',
            new_name='Orders',
        ),
    ]
