# Generated by Django 2.2.19 on 2021-04-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210416_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestoffers',
            name='feature1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bestoffers',
            name='feature2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bestoffers',
            name='feature3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
