# Generated by Django 2.2.19 on 2021-04-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210417_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestoffers',
            name='abl',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='bestoffers',
            name='cover',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='bestoffers',
            name='filament_chamber',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='bestoffers',
            name='ups_module',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='bestoffers',
            name='wifi',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='abl',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cover',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='filament_chamber',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ups_module',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='wifi',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100),
        ),
    ]
