# Generated by Django 2.2.19 on 2021-04-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210417_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abl',
            name='title',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='bedsize',
            name='title',
            field=models.CharField(choices=[('220x220', '220x220'), ('300x300', '300x300'), ('440x440', '440x440'), ('600x600', '600x600')], default='220x220', max_length=100),
        ),
        migrations.AlterField(
            model_name='covered',
            name='title',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='display',
            name='title',
            field=models.CharField(choices=[('touch', 'Touch'), ('knob', 'Knob'), ('touch+knob', 'Touch + Knob')], default='knob', max_length=100),
        ),
        migrations.AlterField(
            model_name='filamentchamber',
            name='title',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='filamentquantity',
            name='title',
            field=models.CharField(choices=[('1kg', '1kg'), ('2kg', '2kg'), ('3kg', '3kg')], default='1kg', max_length=100),
        ),
        migrations.AlterField(
            model_name='height',
            name='title',
            field=models.CharField(choices=[('200', '200'), ('250', '250'), ('300', '300'), ('350', '350'), ('400', '400'), ('450', '450'), ('500', '500'), ('550', '550'), ('600', '600'), ('650', '650'), ('700', '700')], default='200', max_length=100),
        ),
        migrations.AlterField(
            model_name='motordriver',
            name='title',
            field=models.CharField(choices=[('normal', 'Normal'), ('silent', 'Silent')], default='normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='nozzle',
            name='title',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double')], default='single', max_length=100),
        ),
        migrations.AlterField(
            model_name='upsmodule',
            name='title',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='wifi',
            name='title',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100),
        ),
    ]
