# Generated by Django 2.2.19 on 2021-04-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210418_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='height',
            name='bed_size',
            field=models.CharField(choices=[('220x220', '220x220'), ('300x300', '300x300'), ('440x440', '440x440'), ('600x600', '600x600')], default='220x220', max_length=100),
        ),
    ]
