# Generated by Django 2.2.19 on 2021-05-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_height_bed_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsize',
            name='title',
            field=models.CharField(choices=[('220x220', '220x220'), ('300x300', '300x300'), ('400x400', '400x400'), ('440x440', '440x440'), ('600x600', '600x600')], default='220x220', max_length=100),
        ),
        migrations.AlterField(
            model_name='bestoffers',
            name='bed_size',
            field=models.CharField(choices=[('220x220', '220x220'), ('300x300', '300x300'), ('400x400', '400x400'), ('440x440', '440x440'), ('600x600', '600x600')], default='220x220', max_length=100),
        ),
        migrations.AlterField(
            model_name='height',
            name='bed_size',
            field=models.CharField(choices=[('220x220', '220x220'), ('300x300', '300x300'), ('400x400', '400x400'), ('440x440', '440x440'), ('600x600', '600x600')], default='220x220', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='bed_size',
            field=models.CharField(choices=[('220x220', '220x220'), ('300x300', '300x300'), ('400x400', '400x400'), ('440x440', '440x440'), ('600x600', '600x600')], default='220x220', max_length=100),
        ),
    ]
