# Generated by Django 2.2.19 on 2021-05-15 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210515_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.BestOffers')),
            ],
        ),
    ]
