# Generated by Django 2.2.19 on 2021-05-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='abl',
            name='field_name',
            field=models.CharField(default='abl', max_length=100),
        ),
        migrations.AddField(
            model_name='bedsize',
            name='field_name',
            field=models.CharField(default='bed_size', max_length=100),
        ),
        migrations.AddField(
            model_name='covered',
            name='field_name',
            field=models.CharField(default='cover', max_length=100),
        ),
        migrations.AddField(
            model_name='display',
            name='field_name',
            field=models.CharField(default='display', max_length=100),
        ),
        migrations.AddField(
            model_name='filamentchamber',
            name='field_name',
            field=models.CharField(default='filament_chamber', max_length=100),
        ),
        migrations.AddField(
            model_name='filamentquantity',
            name='field_name',
            field=models.CharField(default='filament_quantity', max_length=100),
        ),
        migrations.AddField(
            model_name='height',
            name='field_name',
            field=models.CharField(default='height', max_length=100),
        ),
        migrations.AddField(
            model_name='motordriver',
            name='field_name',
            field=models.CharField(default='motor_driver', max_length=100),
        ),
        migrations.AddField(
            model_name='nozzle',
            name='field_name',
            field=models.CharField(default='nozzle', max_length=100),
        ),
        migrations.AddField(
            model_name='upsmodule',
            name='field_name',
            field=models.CharField(default='ups', max_length=100),
        ),
        migrations.AddField(
            model_name='wifi',
            name='field_name',
            field=models.CharField(default='wifi', max_length=100),
        ),
    ]
