# Generated by Django 2.2.19 on 2021-05-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210516_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abl',
            name='title',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='bedsize',
            name='title',
            field=models.CharField(choices=[('220 X 220', '220 X 220'), ('300 X 300', '300 X 300'), ('400 X 400', '400 X 400'), ('440 X 440', '440 X 440'), ('600 X 600', '600 X 600')], default='220x220', max_length=100),
        ),
        migrations.AlterField(
            model_name='bestoffers',
            name='abl',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='bestoffers',
            name='bed_size',
            field=models.CharField(choices=[('220 X 220', '220 X 220'), ('300 X 300', '300 X 300'), ('400 X 400', '400 X 400'), ('440 X 440', '440 X 440'), ('600 X 600', '600 X 600')], default='220x220', max_length=100),
        ),
        migrations.AlterField(
            model_name='bestoffers',
            name='cover',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='bestoffers',
            name='display',
            field=models.CharField(choices=[('Touch', 'Touch'), ('Knob', 'Knob'), ('Touch + Knob', 'Touch + Knob')], default='knob', max_length=100),
        ),
        migrations.AlterField(
            model_name='bestoffers',
            name='filament_chamber',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='bestoffers',
            name='motor_driver_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Silent', 'Silent')], default='normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='bestoffers',
            name='nozzle',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], default='single', max_length=100),
        ),
        migrations.AlterField(
            model_name='bestoffers',
            name='ups_module',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='bestoffers',
            name='wifi',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='covered',
            name='title',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='display',
            name='title',
            field=models.CharField(choices=[('Touch', 'Touch'), ('Knob', 'Knob'), ('Touch + Knob', 'Touch + Knob')], default='knob', max_length=100),
        ),
        migrations.AlterField(
            model_name='filamentchamber',
            name='title',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='height',
            name='bed_size',
            field=models.CharField(choices=[('220 X 220', '220 X 220'), ('300 X 300', '300 X 300'), ('400 X 400', '400 X 400'), ('440 X 440', '440 X 440'), ('600 X 600', '600 X 600')], default='220x220', max_length=100),
        ),
        migrations.AlterField(
            model_name='motordriver',
            name='title',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Silent', 'Silent')], default='normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='nozzle',
            name='title',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], default='single', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='abl',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='bed_size',
            field=models.CharField(choices=[('220 X 220', '220 X 220'), ('300 X 300', '300 X 300'), ('400 X 400', '400 X 400'), ('440 X 440', '440 X 440'), ('600 X 600', '600 X 600')], default='220x220', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cover',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='display',
            field=models.CharField(choices=[('Touch', 'Touch'), ('Knob', 'Knob'), ('Touch + Knob', 'Touch + Knob')], default='knob', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='filament_chamber',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='motor_driver_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Silent', 'Silent')], default='normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='nozzle',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], default='single', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ups_module',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='wifi',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='upsmodule',
            name='title',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='wifi',
            name='title',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=100),
        ),
    ]
