# Generated by Django 2.2.19 on 2021-05-18 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210516_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id_no',
            field=models.CharField(default=uuid.uuid4, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='user_id_no',
            field=models.CharField(default=uuid.uuid4, max_length=100, null=True),
        ),
    ]
