# Generated by Django 2.2.19 on 2021-05-18 16:15

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210518_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id_no',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='user_id_no',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
