# Generated by Django 2.2.19 on 2021-05-18 17:10

from django.db import migrations, models
import shortuuid

def gen_uuid(apps, schema_editor):
    MyModel1 = apps.get_model('home', 'ProfileInfo')
    for row in MyModel1.objects.all():
        row.user_id_no = shortuuid.uuid(name = row.user.username)
        row.save(update_fields=['user_id_no'])

    MyModel2 = apps.get_model('home', 'Orders')
    for row in MyModel2.objects.all():
        row.order_id_no = shortuuid.uuid(name = str(row.id))
        row.save(update_fields=['order_id_no'])

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210518_1710'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
