# Generated by Django 2.2.19 on 2021-05-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210518_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id_no',
            field=models.CharField(default='RjpCwR7Vg3VQSvQ3iAw6wa', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='user_id_no',
            field=models.CharField(default='Fj7Ac424wSDdYTjuQ3Eqep', max_length=100, unique=True),
        ),
    ]
