# Generated by Django 2.2.19 on 2021-05-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210518_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_id_no',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='user_id_no',
        ),
    ]
