# Generated by Django 2.2.19 on 2021-05-18 17:28

from django.db import migrations, models
import shortuuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210518_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id_no',
            field=models.CharField(default=shortuuid.uuid, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='user_id_no',
            field=models.CharField(default=shortuuid.uuid, max_length=100, null=True),
        ),
    ]
